# Generated by Django 4.0.4 on 2022-04-29 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.IntegerField(choices=[(0, 'received'), (1, 'preparing'), (2, 'complete'), (3, 'cancelled'), (4, 'collect your order')], default=0),
        ),
    ]
